version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    squash_merge_commit_message: "pull-request-title"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
