# This workflow runs whenever a PR is opened or updated, or a commit is pushed to master.
# It checks that the code is formatted properly that it builds successfully.

permissions:
  contents: read

# This configuration allows maintainers of this repo to create a branch and pull request based on
# the new branch. Restricting the push trigger to the master branch ensures that the PR only gets
# built once.
on:
  push:
    branches: [master]
  pull_request:

# If new code is pushed to a PR branch, then cancel in progress workflows for that PR. Ensures that
# we don't waste CI time, and returns results quicker https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: check

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci --no-audit --no-fund --no-progress --loglevel=error
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
